### ISSUE TITLE
Possibility of an open source license?

### ISSUE THREAD

**Issue by harryjmoss** [AlexMoreo/word-class-embeddings#2]
There appears to be no license attached to this project, which makes the code unusable by others ([see this discussion](http://opensource.stackexchange.com/q/1720/775))

If this wasn't intended, could an open source license be added? There are a few example options shown [here](https://choosealicense.com/).

Thanks!

**Comment by AlexMoreo** [comment]
That was not intended indeed. Thanks for pointing this out!
I have now added a BSD-3-Clause license.
